version: '3.3'

services:
    drone-server:
      container_name: drone-server
      image: drone/drone:latest
      ports:
        - 80:8000
        - 9000
      volumes:
        - ./droneDB:/var/lib/drone/
      environment:
        - DRONE_OPEN=true
        - DRONE_HOST=${DRONE_HOST}
        - DRONE_GITHUB=true
        - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
        - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
        - DRONE_SECRET=${DRONE_SECRET}
      restart: always

    drone-agent:
      container_name: drone-agent
      image: drone/agent:latest
      restart: always
      depends_on:
        - drone-server
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - DRONE_SERVER=drone-server:9000
        - DRONE_SECRET=${DRONE_SECRET}
